language: node_js
node_js:
- '5'
branches:
  only:
  - "/^v[0-9]/"
env:
  global: CDN=https://app-hack-build-static.octoblu.com
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
before_deploy:
- npm run build
- export PKG_VERSION="$(node -e 'console.log(require("./package.json").version)')"
- if [ -z "$PKG_VERSION" ]; then echo 'Missing PKG_VERSION env' && exit 1; fi
- mkdir -p dpl_assets/v$PKG_VERSION
- cp -r dist/* dpl_assets/v$PKG_VERSION
deploy:
  matrix:
  - provider: s3
    access_key_id: AKIAIJUBFR55N7FC4I5Q
    secret_access_key:
      secure: K1jRQ/cHwZ/Bl/hWZDQ4Jm/UIxZ1xyaIqY6knZ10a0xKGC8G5hQLi+PWgSlqVH9ed9M2vDyLNyNleNfNYRMgylucUPaz+HLzccuY7BsiNWCi3NmO0MS56A8iZObWU7ZFogth8CyuscVP+abVeqd40HMwB41CkIFMd5Er8+dML9SoXgjMN07LQj2wKfkVK64C1MqEnSfkyvMp4icxAjYE2Vcyf9wXw1aF9prMu3GpKi3XG2znlFmc6AsT+nUCtTRL+hm9VcN29S3qUJY8x0GGQuXvzhlmOP8kdf0amsCdpir3AVFRVArhQbuIa7kES8rmPzoGrFchwV64kr2n3xWHux5jS4kWMiQ4HdAjjf0/UrCWT/JHulTPAvK0RTmhAU5f7ET63AOoIwXkD1hbqPz0Zhr8cf7tuVZ2N8t9aAMnxmhvYDibZhzKGs4KZSLZMIJ3tiT7mDiPmaEXo/nnSv1VMw9LbTkSLRdJXU/SxO9Nkk3IojLOokeMxR7AARzJZy52d5NpqUeHWYM5YnTDHj7Z8SgBaivx+/CLKASVepMVsJq22TI+fXytbSQcHfoA5gCj6vX+fp61vyhuUBmXVpVDeQOci/hmZhZ8wevYeL2+hWHyZ4EBLScuQg8Gee3J3/ItSMJidnGaT8DIGq6Y8CnDwMO9Zcx93yWul78MpxqVN6A=
    bucket: app-hack-build-static.octoblu.com
    local_dir: dpl_assets
    skip_cleanup: true
    region: us-west-2
    on:
      tags: true
